import React from "react";
import "../Styles/Contacts.css";
import ContactRow from "./ContactRow";

function Contacts() {
  return (
    <div className="contacts">
      <h3>Contacts</h3>
      <ContactRow
        src="https://imgur.com/user/cyberavocado21/avatar"
        name="Avoca"
      />
      <ContactRow
        src="https://imgur.com/user/shannonbtweet/avatar"
        name="Barrow"
      />
      <ContactRow
        src="https://imgur.com/user/coreunit/avatar"
        name="Blacwater"
      />
      <ContactRow
        src="https://imgur.com/user/thewholiganofgallifrey/avatar"
        name="Corrib"
      />
      <ContactRow
        src="https://imgur.com/user/coronalmassejection/avatar"
        name="Lennon"
      />
      <ContactRow
        src="https://imgur.com/user/sravicorgibandit/avatar"
        name="Liffey"
      />
      <ContactRow
        src="https://imgur.com/user/imabarroomhero/avatar"
        name="Shannon"
      />
      <ContactRow
        src="https://imgur.com/user/cyberavocado21/avatar"
        name="Avoca"
      />
      <ContactRow
        src="https://imgur.com/user/shannonbtweet/avatar"
        name="Barrow"
      />
      <ContactRow
        src="https://imgur.com/user/coreunit/avatar"
        name="Blacwater"
      />
      <ContactRow
        src="https://imgur.com/user/thewholiganofgallifrey/avatar"
        name="Corrib"
      />
      <ContactRow
        src="https://imgur.com/user/coronalmassejection/avatar"
        name="Lennon"
      />
      <ContactRow
        src="https://imgur.com/user/sravicorgibandit/avatar"
        name="Liffey"
      />
      <ContactRow
        src="https://imgur.com/user/imabarroomhero/avatar"
        name="Shannon"
      />
      <ContactRow
        src="https://imgur.com/user/cyberavocado21/avatar"
        name="Avoca"
      />
      <ContactRow
        src="https://imgur.com/user/shannonbtweet/avatar"
        name="Barrow"
      />
      <ContactRow
        src="https://imgur.com/user/coreunit/avatar"
        name="Blacwater"
      />
      <ContactRow
        src="https://imgur.com/user/thewholiganofgallifrey/avatar"
        name="Corrib"
      />
      <ContactRow
        src="https://imgur.com/user/coronalmassejection/avatar"
        name="Lennon"
      />
      <ContactRow
        src="https://imgur.com/user/sravicorgibandit/avatar"
        name="Liffey"
      />
      <ContactRow
        src="https://imgur.com/user/imabarroomhero/avatar"
        name="Shannon"
      />
      <ContactRow
        src="https://imgur.com/user/cyberavocado21/avatar"
        name="Avoca"
      />
      <ContactRow
        src="https://imgur.com/user/shannonbtweet/avatar"
        name="Barrow"
      />
      <ContactRow
        src="https://imgur.com/user/coreunit/avatar"
        name="Blacwater"
      />
      <ContactRow
        src="https://imgur.com/user/thewholiganofgallifrey/avatar"
        name="Corrib"
      />
      <ContactRow
        src="https://imgur.com/user/coronalmassejection/avatar"
        name="Lennon"
      />
      <ContactRow
        src="https://imgur.com/user/sravicorgibandit/avatar"
        name="Liffey"
      />
      <ContactRow
        src="https://imgur.com/user/imabarroomhero/avatar"
        name="Shannon"
      />
      <ContactRow
        src="https://imgur.com/user/cyberavocado21/avatar"
        name="Avoca"
      />
      <ContactRow
        src="https://imgur.com/user/shannonbtweet/avatar"
        name="Barrow"
      />
      <ContactRow
        src="https://imgur.com/user/coreunit/avatar"
        name="Blacwater"
      />
      <ContactRow
        src="https://imgur.com/user/thewholiganofgallifrey/avatar"
        name="Corrib"
      />
      <ContactRow
        src="https://imgur.com/user/coronalmassejection/avatar"
        name="Lennon"
      />
      <ContactRow
        src="https://imgur.com/user/sravicorgibandit/avatar"
        name="Liffey"
      />
      <ContactRow
        src="https://imgur.com/user/imabarroomhero/avatar"
        name="Shannon"
      />
    </div>
  );
}
export default Contacts;
